version: '3'
services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - prisma
      - mongodb

  prisma:
    image: prismagraphql/prisma:latest
    networks:
      - app-network
    environment:
      DATABASE_URL: "mongodb://mongodb:27017/your-database-name"

  mongodb:
    image: mongo:latest
    networks:
      - app-network
    environment:
      MONGO_INITDB_DATABASE: "your-database-name"

networks:
  app-network:
    driver: bridge
